### ISSUE TITLE
Assembler problems

### ISSUE THREAD

**Issue by rtrussell** [Memotech-Bill/BBCSDL#2]
This instruction is reporting 'Too many parameters':

`ADCS r0, r0, r3
`

The reference I am using for the Cortex-M0+ instruction set is [here](https://developer.arm.com/documentation/ddi0484/b/CHDCICDF).  I am assuming that the assembler is designed to accept 'unified syntax', not the old Thumb16 syntax which is deprecated.

**Comment by rtrussell** [comment]
> The code has now (hopefully) been extended to support all the alternate syntax options.

Thanks.  Unfortunately I've noticed another anomaly; this instruction is being accepted and assembled, but it's not valid for the armv6-m (there's a 32-bit encoding but not a 16-bit encoding):

`ADD r1, r2, r3
`

What seems to be happening is that it is being treated as synonymous with **ADDS r1, r2, r3**  but it's not (ADDS affects the flags, ADD doesn't).

**Comment by Memotech-Bill** [comment]
Try without .syntax unified

**Comment by rtrussell** [comment]
> Try without .syntax unified

If I were to do that the GNU assembler would not accept all the instructions that the Cortex-M0+ can execute, so I don't think it would be very helpful in the context of a BBC BASIC assembler for the Pico.  I would refer you to ARM's own [documentation](https://developer.arm.com/documentation/ddi0484/b/CHDCICDF) for that CPU, which lists amongst the valid instructions:

```
All registers Lo | ADDS Rd, Rn, Rm | 1
Any to Any       | ADD Rd, Rd, Rm  | 1
```

So, unless I'm missing something, both those instructions are legitimate.  It wouldn't be too difficult to test them both on the Pico itself (by poking the hex opcodes into memory); I can try that if you think it would be helpful.

**Comment by Memotech-Bill** [comment]
I have now committed a new file bbasm_arm_v6mu.c (note the 'u' at the end of the filename) which uses unified syntax.

I will continue to consider whether I can add an option to support both forms.

**Comment by Memotech-Bill** [comment]
The ADD bug should be fixed with my latest commit.

**Comment by Memotech-Bill** [comment]
Typo. Fixed.

**Comment by rtrussell** [comment]
> Typo. Fixed.

Getting really close now, as far as my tests can ascertain.  The only things that seem wrong are some directives, for example:

**equb** seemingly incrementing the program counter by 2 rather than 1:
```
[equb &12 : equb &34 : equb &56
0B6B2310 12                   equb &12
0B6B2312 34                   equb &34
0B6B2314 56                   equb &56
```

**align** printing some spurious hex to the listing when no padding is needed:
```
[align 4
0B6B22F0 11 80 00 00          align 4
```

**Comment by Memotech-Bill** [comment]
Hopefully fixed.

**Comment by rtrussell** [comment]
> Hopefully fixed.

We're getting into the realm of subtleties now (important nevertheless).  It looks like your assembler can issue an 'Invalid alignment' error on the **first pass**, because the label it is checking the alignment of hasn't yet been declared (i.e. it's a 'forward reference').   You need to suppress that error until the second pass, when the values of labels are known, otherwise it will abort for no good reason.

**Comment by rtrussell** [comment]
> Hopefully fixed.

I'm pleased to say I haven't found any other encoding errors.  If you're worried about such things, this error message is (at first glance) unhelpful:

```
[add r7,r7,#1
Invalid register
```
It's not the register that's invalid here (there's no alternative register that would make it work) but the use of **add** rather than **adds**.

**Comment by Memotech-Bill** [comment]
> It's not the register that's invalid here (there's no alternative register that would make it work, except SP) but the use of add rather than adds.

The trouble is that

    add r7, r7, #1
    add r9, r9, #1

both hit the same error trap. Only the first one would be valid for **adds**

I am aware of one potential issue:

        align 4
        equb 1
    .label add r0, r0, #2

The label will be evaluated at the odd address before the PC is aligned up to the next even address to insert the instruction.

**Comment by Memotech-Bill** [comment]
I have pushed a small amendment so that the label misalignment is at least visible:

    017B89BE 00 BF                align 4
    017B89C0 01                   dcb 1
    017B89C1 00 01 30    .label   adds r0, r0, #1

**Comment by Memotech-Bill** [comment]
I think I can see how to make a label address match the location of the following opcode. However, consider:

        align 4
        equb 1
    .label1
    .label2 adds r0, r0, #1 

With the modification I am considering, label2 would have the even address of the adds instruction, but label1 will have an odd address. Comments?

**Comment by rtrussell** [comment]
> The label will be evaluated at the odd address before the PC is aligned up to the next even address to insert the instruction.

Checking other versions of BBC BASIC:

Acorn's ARM BASIC V (the 'reference'):
![acorn](https://user-images.githubusercontent.com/42455052/137581763-e39c344f-172d-4d23-9b57-2329a192bc06.png)

BBC BASIC for SDL 2.0 (32-bit ARM):
```
DIM P% 100
[align : equb 1 : .label adds r0,r0,#2
0A691C04                      align
0A691C04 01                   equb 1
0A691C08 E2900002 .label      adds r0,r0,#2
>PRINT ~label
   A691C05
```

So this is **expected** behaviour and should not be changed.

**Comment by rtrussell** [comment]
> So this is **expected** behaviour and should not be changed.

However there _is_ a bug.  On initial entry to the assembler (i.e. after **[)** the program counter should be aligned.  It's important that code like this always sets the label to the address of the instruction and not to an unaligned address:

`[.label nop
`

Currently your assembler does not ensure this.

**Comment by rtrussell** [comment]
> However there _is_ a bug. On initial entry to the assembler (i.e. after **[)** the program counter should be aligned.

This turns out to be a regression.  In **bbasmb_arm_32.c** and **bbasmb_arm_64.c** there's a Boolean **init** which specifically ensures that if a label is declared immediately after the assembler is started, the program counter is aligned.  It looks like you took that out; why?  It's a better solution than unconditionally aligning because it allows this:

```
[equb &12
0B6B1C03 12                   equb &12
[equb &34
0B6B1C04 34                   equb &34
[equb &56
0B6B1C05 56                   equb &56
```
I would encourage you to reinstate the **init** functionality.

**Comment by Memotech-Bill** [comment]
Resinstated init functionality. Align without argument was doing align 2. Now changed to align 4.

I have also committed another version of the assembler in file bbasmb_arm_v6m2.c. This version also uses unified syntax by default, however adding the pseudo-op:

    syntax d

enables the following extensions to the allowed syntax:

- If an opcode takes three arguments and the first and second are the same, then the first may be omitted.
- If the 's' suffix (indicating affects status flags) is omitted from the opcode, but the parameters are only valid for a status affecting instruction, then that is assumed.

The extensions may be disabled again by specifying:

    syntax u

This code has been derived from the checked bbasmb_arm_v6mu.c and hopefully there are no reversions.

The original buggy bbasmb_arm_v6m.c has been deleted.

**Comment by rtrussell** [comment]
> Resinstated init functionality. Align without argument was doing align 2. Now changed to align 4.

Thanks again; I'm not aware of any errors in the assembler now.  There is one remaining issue that I don't know how to resolve:

Judging by what happens currently with the ARM32 assembler on the Pico, it is likely that your assembler will result in alignment faults when writing to non-multiple-of-4 addresses.  But I don't understand why; the **poke()** routine uses **memcpy()** to write to memory, and I thought we had established that it is alignment-safe except when inlined.  And since the byte count is in a variable rather than a constant, I would not expect it to be inlined.

Can you think of any reason why poke() (or anything else in your assembler) might cause an alignment fault, and how to fix it?

**Comment by Memotech-Bill** [comment]
The problems were not in the assembler at all.

All the variables defined in bbdata_arm32.s had become unaligned. Changing the order of the files in CMakeLists.txt to put that file first seems to have resolved the issue.

I did contemplate putting

    .align 4

at the top of that file.

**Comment by rtrussell** [comment]
> All the variables defined in bbdata_arm32.s had become unaligned.

Hmm, I thought that each object module was independently aligned by the linker (probably on at least a 16-byte boundary); I'm almost certain that's the behaviour in Windows, because **.align** directives only align things with respect to the start of that module, so the module must be aligned as well.

Anyway, that doesn't help with the alignment faults arising from the assembler.  I presume that you're seeing them on the Pico in the same way as I am with the ARM32 assembler?

**Comment by rtrussell** [comment]
> no alignment faults seen so far in the assembler.

Odd.  With the ARM32 assembler I'm getting an instant alignment fault from this:

```
BBC BASIC for Pico Console v0.37
(C) Copyright R. T. Russell, 2021
>DIM P% 100
>[equw &1234 : equw &5678
Data alignment fault sr = 0x01000000
R0  = 0x0000003a  R8  = 0x20007703
R1  = 0x20041ce0  R9  = 0x20000858
R2  = 0x20007703  R10 = 0x2000640d
R3  = 0x20007703  R11 = 0x20027700
R4  = 0x00000002  R12 = 0x20007703
R5  = 0x0000000e  SP  = 0x20041cb8
R6  = 0x20007703  LR  = 0x1000b05d
R7  = 0x20006401  PC  = 0x1000b19a
 -> unaligned access to 0x20007703
```

Given that I don't believe the code for **equw** is different in your version I wonder what accounts for this.  Of course I'm using Eric's build, but I assume you and he are using the same version of the SDK.

**Comment by Memotech-Bill** [comment]
Result posted on the [Raspberry Pi Forum](https://forums.raspberrypi.com/viewtopic.php?f=144&t=316761&p=1925756#p1925756)
