### ISSUE TITLE
Wrong examples being bundled with Pico console edition

### ISSUE THREAD

**Issue by rtrussell** [Memotech-Bill/BBCSDL#3]
It appears that some of the example programs bundled with the Pico console edition are GUI versions, which can't run, rather than the correct console versions.  Specifically these are **calendar.bbc**, **hanoi.bbc**, **sortdemo.bbc**, **sudoku.bbc** and **timing.bbc**.  The code at fault seems to be [here](https://github.com/Memotech-Bill/BBCSDL/blob/master/src/lfsutil/Makefile):

```
	cp ../../BBCSDL/examples/general/calendar.bbc tree/
	cp ../../BBCSDL/examples/general/sortdemo.bbc tree/
	for i in hanoi.bbc sudoku.bbc sudoku.dat; \
		do cp ../../BBCSDL/examples/games/$$i tree/$$i; done 
	cp ../../BBCSDL/examples/tools/timing.bbc tree/
```
Probably it should be deleted.

**Comment by Memotech-Bill** [comment]
Makefile has now been revised to use programs from console/pico/examples rather than from upstream repository.
